/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.adc.ADCManager */

#ifndef __NATIVE_ADCMANAGER_H__
#define __NATIVE_ADCMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_adc_ADCManager
 * Method:    init0
 * Signature: ()I
 */
void Java_iot_oem_adc_ADCManager_init0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_adc_ADCManager
 * Method:    read0
 * Signature: (I)I
 */
void Java_iot_oem_adc_ADCManager_read0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_adc_ADCManager
 * Method:    destroy0
 * Signature: ()I
 */
void Java_iot_oem_adc_ADCManager_destroy0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_ADCMANAGER_H__
