/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.usb.USBConnection */

#ifndef __NATIVE_USBCONNECTION_H__
#define __NATIVE_USBCONNECTION_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_usb_USBConnection
 * Method:    open0
 * Signature: (Ljava/lang/String;)I
 */
void Java_iot_oem_usb_USBConnection_open0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_usb_USBConnection
 * Method:    close0
 * Signature: (I)I
 */
void Java_iot_oem_usb_USBConnection_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_USBCONNECTION_H__
