/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.comm.CommConnectionImpl */

#ifndef __NATIVE_COMMCONNECTIONIMPL_H__
#define __NATIVE_COMMCONNECTIONIMPL_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_comm_CommConnectionImpl
 * Method:    open0
 * Signature: (II)I
 */
void Java_iot_oem_comm_CommConnectionImpl_open0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_comm_CommConnectionImpl
 * Method:    getBaudRate0
 * Signature: (I)I
 */
void Java_iot_oem_comm_CommConnectionImpl_getBaudRate0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_comm_CommConnectionImpl
 * Method:    setBaudRate0
 * Signature: (II)I
 */
void Java_iot_oem_comm_CommConnectionImpl_setBaudRate0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_comm_CommConnectionImpl
 * Method:    close0
 * Signature: (I)I
 */
void Java_iot_oem_comm_CommConnectionImpl_close0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_comm_CommConnectionImpl
 * Method:    writeBytes0
 * Signature: (I[BII)I
 */
void Java_iot_oem_comm_CommConnectionImpl_writeBytes0(const u4*args, JValue* pResult);

/**
 * Class:     iot_oem_comm_CommConnectionImpl
 * Method:    readBytes0
 * Signature:  (I[BII)I
 */
void Java_iot_oem_comm_CommConnectionImpl_readBytes0(const u4*args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_COMMCONNECTIONIMPL_H__
