/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.battery.BatteryManager */

#ifndef __NATIVE_BATTERYMANAGER_H__
#define __NATIVE_BATTERYMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_battery_BatteryManager
 * Method:    getStatus0
 * Signature: ()I
 */
void Java_iot_oem_battery_BatteryManager_getStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_battery_BatteryManager
 * Method:    getTemperature0
 * Signature: ()I
 */
void Java_iot_oem_battery_BatteryManager_getTemperature0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_BATTERYMANAGER_H__
