/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.gpio.Gpio */

#ifndef __NATIVE_GPIO_H__
#define __NATIVE_GPIO_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    open0
 * Signature: (I)I
 */
void Java_iot_oem_gpio_Gpio_open0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    setCurrentMode0
 * Signature: (II)I
 */
void Java_iot_oem_gpio_Gpio_setCurrentMode0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    getCurrentMode0
 * Signature: (I)I
 */
void Java_iot_oem_gpio_Gpio_getCurrentMode0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    read0
 * Signature: (I)I
 */
void Java_iot_oem_gpio_Gpio_read0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    write0
 * Signature: (IZ)I
 */
void Java_iot_oem_gpio_Gpio_write0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    registerInt0
 * Signature: (II)I
 */
void Java_iot_oem_gpio_Gpio_registerInt0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    unregisterInt0
 * Signature: (I)I
 */
void Java_iot_oem_gpio_Gpio_unregisterInt0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_gpio_Gpio
 * Method:    close0
 * Signature: (I)I
 */
void Java_iot_oem_gpio_Gpio_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_GPIO_H__
