/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.lang.Math */

#ifndef __NATIVE_MATH_H__
#define __NATIVE_MATH_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_lang_Math
 * Method:    cos
 * Signature: (D)D
 */
void Java_java_lang_Math_cos(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Math
 * Method:    sin
 * Signature: (D)D
 */
void Java_java_lang_Math_sin(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Math
 * Method:    sqrt
 * Signature: (D)D
 */
void Java_java_lang_Math_sqrt(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Math
 * Method:    tan
 * Signature: (D)D
 */
void Java_java_lang_Math_tan(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_MATH_H__
