/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class jp.co.cmcc.atcommand.ATCommandConnection */

#ifndef __NATIVE_ATCOMMANDCONNECTION_H__
#define __NATIVE_ATCOMMANDCONNECTION_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     jp_co_cmcc_atcommand_ATCommandConnection
 * Method:    open0
 * Signature: ()I
 */
void Java_jp_co_cmcc_atcommand_ATCommandConnection_open0(const u4* args, JValue* pResult);

/**
 * Class:     jp_co_cmcc_atcommand_ATCommandConnection
 * Method:    send0
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
void Java_jp_co_cmcc_atcommand_ATCommandConnection_send0(const u4* args, JValue* pResult);

/**
 * Class:     jp_co_cmcc_atcommand_ATCommandConnection
 * Method:    sendAsyn0
 * Signature: (Ljava/lang/String;)I
 */
void Java_jp_co_cmcc_atcommand_ATCommandConnection_sendAsyn0(const u4* args, JValue* pResult);

/**
 * Class:     jp_co_cmcc_atcommand_ATCommandConnection
 * Method:    get0
 * Signature: ()Ljava/lang/String;
 */
void Java_jp_co_cmcc_atcommand_ATCommandConnection_get0(const u4* args, JValue* pResult);

/**
 * Class:     jp_co_cmcc_atcommand_ATCommandConnection
 * Method:    close0
 * Signature: ()I
 */
void Java_jp_co_cmcc_atcommand_ATCommandConnection_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_ATCOMMANDCONNECTION_H__
