/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.lang.Double */

#ifndef __NATIVE_DOUBLE_H__
#define __NATIVE_DOUBLE_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef union Convert64_u {
    u4 arg[2];
    s8 ll;
    double dd;
} Convert64;

typedef union IEEEd2bits_u {
    double d;
    struct {
#ifdef  DVM_BIG_ENDIAN
        unsigned int sign : 1;
        unsigned int exp : 11;
        unsigned int manh : 20;
        unsigned int manl : 32;
#else
        unsigned int manl : 32;
        unsigned int manh : 20;
        unsigned int exp : 11;
        unsigned int sign : 1;
#endif
    } bits;
} IEEEd2bits;

/**
 * Class:     java_lang_Double
 * Method:    doubleToLongBits
 * Signature: (D)J
 *
 * Returns an integer corresponding to the bits of the given
 * <a href="http://en.wikipedia.org/wiki/IEEE_754-1985">IEEE 754</a> double precision
 * {@code value}. All <em>Not-a-Number (NaN)</em> values are converted to a single NaN
 * representation ({@code 0x7ff8000000000000L}) (compare to {@link #doubleToRawLongBits}).
 */
void Java_java_lang_Double_doubleToLongBits(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Double
 * Method:    doubleToRawLongBits
 * Signature: (D)J
 *
 * Returns an integer corresponding to the bits of the given
 * <a href="http://en.wikipedia.org/wiki/IEEE_754-1985">IEEE 754</a> double precision
 * {@code value}. <em>Not-a-Number (NaN)</em> values are preserved (compare
 * to {@link #doubleToLongBits}).
 */
void Java_java_lang_Double_doubleToRawLongBits(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Double
 * Method:    longBitsToDouble
 * Signature: (J)D
 *
 * Returns the <a href="http://en.wikipedia.org/wiki/IEEE_754-1985">IEEE 754</a>
 * double precision float corresponding to the given {@code bits}.
 */
void Java_java_lang_Double_longBitsToDouble(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_DOUBLE_H__
