/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class jp.co.cmcc.message.sms.MyMessageSender */

#ifndef __NATIVE_MYMESSAGESENDER_H__
#define __NATIVE_MYMESSAGESENDER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     jp_co_cmcc_message_sms_MyMessageSender
 * Method:    nSend
 * Signature: (Ljava/lang/String;III[BI)Z
 */
void Java_jp_co_cmcc_message_sms_MyMessageSender_nSend(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_MYMESSAGESENDER_H__
