/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.io.FileOutputStream */

#ifndef __NATIVE_FILEOUTPUTSTREAM_H__
#define __NATIVE_FILEOUTPUTSTREAM_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_io_FileOutputStream
 * Method:    writeFile
 * Signature: (I[BII)I
 */
void Java_java_io_FileOutputStream_writeFile(const u4* args, JValue* pResult);

/**
 * Class:     java_io_FileOutputStream
 * Method:    openFile
 * Signature: (Ljava/lang/String;Z)I
 */
void Java_java_io_FileOutputStream_openFile(const u4* args, JValue* pResult);

/**
 * Class:     java_io_FileOutputStream
 * Method:    closeFile
 * Signature: (I)Z
 */
void Java_java_io_FileOutputStream_closeFile(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_FILEOUTPUTSTREAM_H__
