/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.lang.Double */

#ifndef __NATIVE_DOUBLE_H__
#define __NATIVE_DOUBLE_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_lang_Double
 * Method:    doubleToLongBits
 * Signature: (D)J
 */
void Java_java_lang_Double_doubleToLongBits(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Double
 * Method:    doubleToRawLongBits
 * Signature: (D)J
 */
void Java_java_lang_Double_doubleToRawLongBits(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Double
 * Method:    longBitsToDouble
 * Signature: (J)D
 */
void Java_java_lang_Double_longBitsToDouble(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_DOUBLE_H__
