/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.ear.EarManager */

#ifndef __NATIVE_EARMANAGER_H__
#define __NATIVE_EARMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_ear_EarManager
 * Method:    init0
 * Signature: ()I
 */
void Java_iot_oem_ear_EarManager_init0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_ear_EarManager
 * Method:    getStatus0
 * Signature: ()I
 */
void Java_iot_oem_ear_EarManager_getStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_ear_EarManager
 * Method:    setStatus0
 * Signature: (Z)I
 */
void Java_iot_oem_ear_EarManager_setStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_ear_EarManager
 * Method:    close0
 * Signature: ()I
 */
void Java_iot_oem_ear_EarManager_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_EARMANAGER_H__
