/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.sim.SimManager */

#ifndef __NATIVE_SIMMANAGER_H__
#define __NATIVE_SIMMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_sim_SimManager
 * Method:    close0
 * Signature: ()I
 */
void Java_iot_oem_sim_SimManager_close0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_sim_SimManager
 * Method:    enablePinLock0
 * Signature: (Ljava/lang/String;)I
 */
void Java_iot_oem_sim_SimManager_enablePinLock0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_sim_SimManager
 * Method:    disablePinLock0
 * Signature: (Ljava/lang/String;)I
 */
void Java_iot_oem_sim_SimManager_disablePinLock0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_sim_SimManager
 * Method:    unlockPin0
 * Signature: (Ljava/lang/String;)I
 */
void Java_iot_oem_sim_SimManager_unlockPin0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_sim_SimManager
 * Method:    changePin0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
void Java_iot_oem_sim_SimManager_changePin0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_SIMMANAGER_H__
