/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.spk.SpeakerManager */

#ifndef __NATIVE_SPEAKERMANAGER_H__
#define __NATIVE_SPEAKERMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_spk_SpeakerManager
 * Method:    init0
 * Signature: ()I
 */
void Java_iot_oem_spk_SpeakerManager_init0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spk_SpeakerManager
 * Method:    getStatus0
 * Signature: ()I
 */
void Java_iot_oem_spk_SpeakerManager_getStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spk_SpeakerManager
 * Method:    setStatus0
 * Signature: (Z)I
 */
void Java_iot_oem_spk_SpeakerManager_setStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spk_SpeakerManager
 * Method:    close0
 * Signature: ()I
 */
void Java_iot_oem_spk_SpeakerManager_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_SPEAKERMANAGER_H__
