/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.net.ota.OTADownload */

#ifndef __NATIVE_OTADOWNLOAD_H__
#define __NATIVE_OTADOWNLOAD_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_net_ota_OTADownload
 * Method:    getAppInstalledDir
 * Signature: ()Ljava/lang/String;
 */
void Java_java_net_ota_OTADownload_getAppInstalledDir(const u4* args, JValue* pResult);

/**
 * Class:     java_net_ota_OTADownload
 * Method:    notifyOTAResult0
 * Signature: (I)V
 */
void Java_java_net_ota_OTADownload_notifyOTAResult0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_OTADOWNLOAD_H__
