/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.lang.Object */

#ifndef __NATIVE_OBJECT_H__
#define __NATIVE_OBJECT_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_lang_Object
 * Method:    internalClone
 * Signature: (Ljava/lang/Cloneable;)Ljava/lang/Object;
 */
void Java_java_lang_Object_internalClone(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Object
 * Method:    getClass
 * Signature: ()Ljava/lang/Class;
 */
void Java_java_lang_Object_getClass(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Object
 * Method:    hashCode
 * Signature: ()I
 */
void Java_java_lang_Object_hashCode(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Object
 * Method:    notify
 * Signature: ()V
 */
void Java_java_lang_Object_notify(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Object
 * Method:    notifyAll
 * Signature: ()V
 */
void Java_java_lang_Object_notifyAll(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Object
 * Method:    wait
 * Signature: (JI)V
 */
void Java_java_lang_Object_wait(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_OBJECT_H__
