/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.pwm.PWMManager */

#ifndef __NATIVE_PWMMANAGER_H__
#define __NATIVE_PWMMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_pwm_PWMManager
 * Method:    config0
 * Signature: (III)I
 */
void Java_iot_oem_pwm_PWMManager_config0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pwm_PWMManager
 * Method:    command0
 * Signature: (III)I
 */
void Java_iot_oem_pwm_PWMManager_command0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_PWMMANAGER_H__
