/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class com.yarlungsoft.ams.Scheduler */

#ifndef __NATIVE_SCHEDULER_H__
#define __NATIVE_SCHEDULER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     com_yarlungsoft_ams_Scheduler
 * Method:    reportState
 * Signature: (I)V
 */
void Java_com_yarlungsoft_ams_Scheduler_reportState(const u4* args, JValue* pResult);

/**
 * Class:     com_yarlungsoft_ams_Scheduler
 * Method:    reportRunningObject
 * Signature: (Ljava/lang/Object;)V
 */
void Java_com_yarlungsoft_ams_Scheduler_reportRunningObject(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_SCHEDULER_H__
