/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.NativeAPI.NativeAPIManager */

#ifndef __NATIVE_NATIVE_APIMANAGER_H__
#define __NATIVE_NATIVE_APIMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_NativeAPI_NativeAPIManager
 * Method:    init0
 * Signature: ()I
 */
void Java_iot_oem_NativeAPI_NativeAPIManager_init0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_NativeAPI_NativeAPIManager
 * Method:    call0
 * Signature: (IZ)I
 */
void Java_iot_oem_NativeAPI_NativeAPIManager_call0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_NativeAPI_NativeAPIManager
 * Method:    destroy0
 * Signature: (I)I
 */
void Java_iot_oem_NativeAPI_NativeAPIManager_destroy0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_NATIVE_APIMANAGER_H__
