/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.lcd.LCD */

#ifndef __NATIVE_LCD_H__
#define __NATIVE_LCD_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_lcd_LCD
 * Method:    setBackgroundStatus0
 * Signature: (Z)I
 */
void Java_iot_oem_lcd_LCD_setBackgroundStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_lcd_LCD
 * Method:    getBackgroundStatus0
 * Signature: ()I
 */
void Java_iot_oem_lcd_LCD_getBackgroundStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_lcd_LCD
 * Method:    getHeight0
 * Signature: ()I
 */
void Java_iot_oem_lcd_LCD_getHeight0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_lcd_LCD
 * Method:    getWidth0
 * Signature: ()I
 */
void Java_iot_oem_lcd_LCD_getWidth0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_lcd_LCD
 * Method:    drawString0
 * Signature: (IILjava/lang/String;)I
 */
void Java_iot_oem_lcd_LCD_drawString0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_lcd_LCD
 * Method:    clean0
 * Signature: ()I
 */
void Java_iot_oem_lcd_LCD_clean0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_LCD_H__
