/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class com.yarlungsoft.util.SystemPrintStream */

#ifndef __NATIVE_SYSTEMPRINTSTREAM_H__
#define __NATIVE_SYSTEMPRINTSTREAM_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     com_yarlungsoft_util_SystemPrintStream
 * Method:    flush
 * Signature: ()V
 */
void Java_com_yarlungsoft_util_SystemPrintStream_flush(const u4* args, JValue* pResult);

/**
 * Class:     com_yarlungsoft_util_SystemPrintStream
 * Method:    write
 * Signature: (I)V
 */
void Java_com_yarlungsoft_util_SystemPrintStream_write(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_SYSTEMPRINTSTREAM_H__
