/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class com.yarlungsoft.ams.Main */

#ifndef __NATIVE_MAIN_H__
#define __NATIVE_MAIN_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     com_yarlungsoft_ams_Main
 * Method:    loadClassByPath0
 * Signature: (Ljava/lang/String;)V
 */
void Java_com_yarlungsoft_ams_Main_loadClassByPath0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_MAIN_H__
