/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class com.yarlungsoft.util.SystemInputStream */

#ifndef __NATIVE_SYSTEMINPUTSTREAM_H__
#define __NATIVE_SYSTEMINPUTSTREAM_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     com_yarlungsoft_util_SystemInputStream
 * Method:    readN
 * Signature: ([BII)I
 */
void Java_com_yarlungsoft_util_SystemInputStream_readN(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_SYSTEMINPUTSTREAM_H__
