/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.spi.SPIManager */

#ifndef __NATIVE_SPIMANAGER_H__
#define __NATIVE_SPIMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_spi_SPIManager
 * Method:    open0
 * Signature: (II)I
 */
void Java_iot_oem_spi_SPIManager_open0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spi_SPIManager
 * Method:    getRate0
 * Signature: (I)I
 */
void Java_iot_oem_spi_SPIManager_getRate0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spi_SPIManager
 * Method:    setRate0
 * Signature: (II)I
 */
void Java_iot_oem_spi_SPIManager_setRate0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spi_SPIManager
 * Method:    close0
 * Signature: (I)I
 */
void Java_iot_oem_spi_SPIManager_close0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spi_SPIManager
 * Method:    read0
 * Signature: (II[BI)I
 */
void Java_iot_oem_spi_SPIManager_read0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_spi_SPIManager
 * Method:    write0
 * Signature: (II[BI)I
 */
void Java_iot_oem_spi_SPIManager_write0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_SPIMANAGER_H__
