/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.io.FileInputStream */

#ifndef __NATIVE_FILEINPUTSTREAM_H__
#define __NATIVE_FILEINPUTSTREAM_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_io_FileInputStream
 * Method:    openFile
 * Signature: (Ljava/lang/String;)I
 */
void Java_java_io_FileInputStream_openFile(const u4* args, JValue* pResult);

/**
 * Class:     java_io_FileInputStream
 * Method:    closeFile
 * Signature: (I)Z
 */
void Java_java_io_FileInputStream_closeFile(const u4* args, JValue* pResult);

/**
 * Class:     java_io_FileInputStream
 * Method:    readFile
 * Signature: (I[BII)I
 */
void Java_java_io_FileInputStream_readFile(const u4* args, JValue* pResult);

/**
 * Class:     java_io_FileInputStream
 * Method:    available0
 * Signature: (I)I
 */
void Java_java_io_FileInputStream_available0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_FileInputStream
 * Method:    skip0
 * Signature: (IJ)J
 */
void Java_java_io_FileInputStream_skip0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_FILEINPUTSTREAM_H__
