/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.kpd.RawKeyPdDriver */

#ifndef __NATIVE_RAWKEYPDDRIVER_H__
#define __NATIVE_RAWKEYPDDRIVER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_kpd_RawKeyPdDriver
 * Method:    init0
 * Signature: ()I
 */
void Java_iot_oem_kpd_RawKeyPdDriver_init0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_kpd_RawKeyPdDriver
 * Method:    getKey0
 * Signature: ()J
 */
void Java_iot_oem_kpd_RawKeyPdDriver_getKey0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_kpd_RawKeyPdDriver
 * Method:    close0
 * Signature: ()I
 */
void Java_iot_oem_kpd_RawKeyPdDriver_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_RAWKEYPDDRIVER_H__
