/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.io.File */

#ifndef __NATIVE_FILE_H__
#define __NATIVE_FILE_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_io_File
 * Method:    createFile0
 * Signature: (Ljava/lang/String;)Z
 */
void Java_java_io_File_createFile0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    delete0
 * Signature: (Ljava/lang/String;)Z
 */
void Java_java_io_File_delete0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    exists0
 * Signature: (Ljava/lang/String;)Z
 */
void Java_java_io_File_exists0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    isDirectory0
 * Signature: (Ljava/lang/String;)Z
 */
void Java_java_io_File_isDirectory0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    isFile0
 * Signature: (Ljava/lang/String;)Z
 */
void Java_java_io_File_isFile0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    lastModified0
 * Signature: (Ljava/lang/String;)J
 */
void Java_java_io_File_lastModified0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    length0
 * Signature: (Ljava/lang/String;)J
 */
void Java_java_io_File_length0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    list0
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
void Java_java_io_File_list0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    totalSize0
 * Signature: (Ljava/lang/String;)J
 */
void Java_java_io_File_totalSize0(const u4* args, JValue* pResult);

/**
 * Class:     java_io_File
 * Method:    availableSize0
 * Signature: (Ljava/lang/String;)J
 */
void Java_java_io_File_availableSize0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_FILE_H__
