/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class jp.co.cmcc.message.sms.MySmsConnectionThread */

#ifndef __NATIVE_MYSMSCONNECTIONTHREAD_H__
#define __NATIVE_MYSMSCONNECTIONTHREAD_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     jp_co_cmcc_message_sms_MySmsConnectionThread
 * Method:    nReadMessage
 * Signature: ()Z
 */
void Java_jp_co_cmcc_message_sms_MySmsConnectionThread_nReadMessage(const u4* args, JValue* pResult);

/**
 * Class:     jp_co_cmcc_message_sms_MySmsConnectionThread
 * Method:    nDeleteMessage
 * Signature: ()V
 */
void Java_jp_co_cmcc_message_sms_MySmsConnectionThread_nDeleteMessage(const u4* args, JValue* pResult);

/**
 * Class:     jp_co_cmcc_message_sms_MySmsConnectionThread
 * Method:    nRegister
 * Signature: ()Z
 */
void Java_jp_co_cmcc_message_sms_MySmsConnectionThread_nRegister(const u4* args, JValue* pResult);

/**
 * Class:     jp_co_cmcc_message_sms_MySmsConnectionThread
 * Method:    nUnregister
 * Signature: ()V
 */
void Java_jp_co_cmcc_message_sms_MySmsConnectionThread_nUnregister(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_MYSMSCONNECTIONTHREAD_H__
