/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.i2c.I2CManager */

#ifndef __NATIVE_I2CMANAGER_H__
#define __NATIVE_I2CMANAGER_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_i2c_I2CManager
 * Method:    open0
 * Signature: (IIII)I
 */
void Java_iot_oem_i2c_I2CManager_open0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_i2c_I2CManager
 * Method:    getRate0
 * Signature: (I)I
 */
void Java_iot_oem_i2c_I2CManager_getRate0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_i2c_I2CManager
 * Method:    setRate0
 * Signature: (II)I
 */
void Java_iot_oem_i2c_I2CManager_setRate0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_i2c_I2CManager
 * Method:    close0
 * Signature: (I)I
 */
void Java_iot_oem_i2c_I2CManager_close0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_i2c_I2CManager
 * Method:    read0
 * Signature: (III[BI)I
 */
void Java_iot_oem_i2c_I2CManager_read0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_i2c_I2CManager
 * Method:    write0
 * Signature: (III[BI)I
 */
void Java_iot_oem_i2c_I2CManager_write0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_I2CMANAGER_H__
