/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class com.yarlungsoft.util.Device */

#ifndef __NATIVE_DEVICE_H__
#define __NATIVE_DEVICE_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     com_yarlungsoft_util_Device
 * Method:    getImei0
 * Signature: ()Ljava/lang/String;
 */
void Java_com_yarlungsoft_util_Device_getImei0(const u4* args, JValue* pResult);

/**
 * Class:     com_yarlungsoft_util_Device
 * Method:    restartDevice0
 * Signature: ()V
 */
void Java_com_yarlungsoft_util_Device_restartDevice0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_DEVICE_H__
