/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.micophone.Micophone */

#ifndef __NATIVE_MICOPHONE_H__
#define __NATIVE_MICOPHONE_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    open0
 * Signature: ()I
 */
void Java_iot_oem_micophone_Micophone_open0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    getStatus0
 * Signature: ()I
 */
void Java_iot_oem_micophone_Micophone_getStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    setStatus0
 * Signature: (Z)I
 */
void Java_iot_oem_micophone_Micophone_setStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    getInPath0
 * Signature: ()I
 */
void Java_iot_oem_micophone_Micophone_getInPath0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    setInPath0
 * Signature: (I)I
 */
void Java_iot_oem_micophone_Micophone_setInPath0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    getGain0
 * Signature: ()I
 */
void Java_iot_oem_micophone_Micophone_getGain0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    setGain0
 * Signature: (I)I
 */
void Java_iot_oem_micophone_Micophone_setGain0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_micophone_Micophone
 * Method:    close0
 * Signature: ()I
 */
void Java_iot_oem_micophone_Micophone_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_MICOPHONE_H__
