/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.util.TimeZone */

#ifndef __NATIVE_TIMEZONE_H__
#define __NATIVE_TIMEZONE_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_util_TimeZone
 * Method:    getDefaultId
 * Signature: ()Ljava/lang/String;
 */
void Java_java_util_TimeZone_getDefaultId(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_TIMEZONE_H__
