/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class iot.oem.pcmchannel.PCMChannel */

#ifndef __NATIVE_PCMCHANNEL_H__
#define __NATIVE_PCMCHANNEL_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    open0
 * Signature: ()I
 */
void Java_iot_oem_pcmchannel_PCMChannel_open0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    getStatus0
 * Signature: ()I
 */
void Java_iot_oem_pcmchannel_PCMChannel_getStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    setStatus0
 * Signature: (Z)I
 */
void Java_iot_oem_pcmchannel_PCMChannel_setStatus0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    getFrequency0
 * Signature: ()I
 */
void Java_iot_oem_pcmchannel_PCMChannel_getFrequency0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    setFrequency0
 * Signature: (I)I
 */
void Java_iot_oem_pcmchannel_PCMChannel_setFrequency0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    getMode0
 * Signature: ()I
 */
void Java_iot_oem_pcmchannel_PCMChannel_getMode0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    setMode0
 * Signature: (I)I
 */
void Java_iot_oem_pcmchannel_PCMChannel_setMode0(const u4* args, JValue* pResult);

/**
 * Class:     iot_oem_pcmchannel_PCMChannel
 * Method:    close0
 * Signature: ()I
 */
void Java_iot_oem_pcmchannel_PCMChannel_close0(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_PCMCHANNEL_H__
