/* DO NOT EDIT THIS FILE - it is machine generated */
#include <dthing.h>
#include <kni.h>

/* Header for class java.lang.Runtime */

#ifndef __NATIVE_RUNTIME_H__
#define __NATIVE_RUNTIME_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class:     java_lang_Runtime
 * Method:    freeMemory
 * Signature: ()J
 */
void Java_java_lang_Runtime_freeMemory(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Runtime
 * Method:    totalMemory
 * Signature: ()J
 */
void Java_java_lang_Runtime_totalMemory(const u4* args, JValue* pResult);

/**
 * Class:     java_lang_Runtime
 * Method:    gc
 * Signature: ()V
 */
void Java_java_lang_Runtime_gc(const u4* args, JValue* pResult);

#ifdef __cplusplus
}
#endif
#endif // __NATIVE_RUNTIME_H__
