. build.sh ADCDemo
. build.sh ATCDemo
. build.sh AudioDemo
. build.sh BuzzerDemo
. build.sh COMDemo
. build.sh CoTestDemo
. build.sh GPIODemo
. build.sh GPSDemo
. build.sh GSensorDemo
. build.sh HeartDemo
. build.sh HelloDemo
. build.sh I2CDemo
. build.sh IRCDemo
. build.sh IRDistanceDemo
. build.sh JSDDemo
. build.sh KeypadDemo
. build.sh KeyPadLed
. build.sh LEDDemo
. build.sh PWMDemo
. build.sh QTDemo
. build.sh ShakeDemo
. build.sh ThreadDemo
. build.sh Ublox
. build.sh Vibrate
. build.sh WSDDemo
. build.sh WSDDemo2
. build.sh ZigbeeDemo
. build.sh ZigbeeDemoNoNet
. build.sh ZigbeeDemoNoCom
. build.sh ZigbeeDemoNoComModiNet


